export const seedUsers = [
  {
    name: 'Sarah Jenkins',
    email: 'admin@exportflow.com',
    password: 'password123',
    role: 'Admin',
  },
  {
    name: 'Michael Vance',
    email: 'manager@exportflow.com',
    password: 'password123',
    role: 'Manager',
  },
  {
    name: 'Alex Rivera',
    email: 'sales@exportflow.com',
    password: 'password123',
    role: 'Sales',
  },
];

export const seedCompanies = [
  {
    companyName: 'Hanseatic Maschinenbau GmbH',
    website: 'https://hanseatic-maschinenbau.de',
    country: 'Germany',
    industry: 'Industrial Machinery',
    productInterest: 'Industrial Valves & Actuators',
    description: 'Major German OEM manufacturer of heavy industrial machinery and hydraulic systems based in Hamburg.',
    employeeCount: '500-1000',
    hsCodes: ['8481.80.10'],
    primaryStandards: ['ASME B16.34', 'DIN EN 10204 3.1'],
    preferredIncoterms: 'CIF',
    annualImportVolume: '$2.5M - $5M',
    source: 'Hannover Messe Directory',
  },
  {
    companyName: 'Apex Fluid Controls LLC',
    website: 'https://apexfluidcontrols.com',
    country: 'USA',
    industry: 'Engineering & Controls',
    productInterest: 'Submersible Slurry Pumps',
    description: 'Texas-based distributor of high-pressure fluid pumps and valve assemblies for petrochemical plants.',
    employeeCount: '250-500',
    hsCodes: ['8413.70.20'],
    primaryStandards: ['ANSI/HI 1.3', 'ISO 5199'],
    preferredIncoterms: 'FOB',
    annualImportVolume: '$1M - $2.5M',
    source: 'US Import Manifest Data',
  },
  {
    companyName: 'Gulf Power Equipment Trading FZE',
    website: 'https://gulfpowerequip.ae',
    country: 'UAE',
    industry: 'Electrical Equipment',
    productInterest: 'High Voltage Transformers',
    description: 'Leading Dubai importer and wholesaler of power transmission transformers and heavy electrical switchgear.',
    employeeCount: '100-250',
    hsCodes: ['8504.23.00'],
    primaryStandards: ['IEC 60076', 'IEEE C57'],
    preferredIncoterms: 'CIF',
    annualImportVolume: '$5M+',
    source: 'Dubai Trade Expo 2026',
  },
  {
    companyName: 'Nippon Precision Drive Corp',
    website: 'https://nipponprecisiondrive.co.jp',
    country: 'Japan',
    industry: 'Manufacturing Equipment',
    productInterest: 'CNC Machine Components & Gears',
    description: 'Precision machining manufacturer requiring custom forged steel gears and CNC spindle components in Osaka.',
    employeeCount: '1000+',
    hsCodes: ['8483.40.10'],
    primaryStandards: ['AGMA 2001', 'ISO 6336'],
    preferredIncoterms: 'CFR',
    annualImportVolume: '$500k - $1M',
    source: 'JMTBA Trade Association',
  },
  {
    companyName: 'Equipamentos Industriais Brasil Ltda',
    website: 'https://equipamentosbrasil.com.br',
    country: 'Brazil',
    industry: 'Industrial Supplies',
    productInterest: 'Hydraulic Fittings & Flanges',
    description: 'São Paulo supplier of heavy hydraulic fittings, forged flanges, and industrial pipe connectors.',
    employeeCount: '50-100',
    hsCodes: ['7307.91.00'],
    primaryStandards: ['SAE J514', 'ISO 8434-1'],
    preferredIncoterms: 'FOB',
    annualImportVolume: '$250k - $500k',
    source: 'Direct Web Inquiry',
  },
];

export const seedLeads = [
  {
    companyName: 'Hanseatic Maschinenbau GmbH',
    contactName: 'Dr. Klaus Becker',
    jobTitle: 'Head of Global Procurement',
    email: 'k.becker@hanseatic-maschinenbau.de',
    phone: '+49 40 8912 3400',
    website: 'https://hanseatic-maschinenbau.de',
    country: 'Germany',
    city: 'Hamburg',
    industry: 'Industrial Machinery',
    productInterest: 'Industrial Valves & Actuators',
    buyerType: 'Importer',
    hsCode: '8481.80.10',
    technicalStandards: ['ASME B16.34', 'DIN EN 10204 3.1', 'API 6D'],
    certificationsRequired: ['CE Mark', 'ISO 9001:2015', 'EN 10204 3.1 MTR'],
    preferredIncoterms: 'CIF',
    targetPort: 'Port of Hamburg',
    roleCategory: 'Procurement',
    annualImportVolume: '$2.5M - $5M',
    companyDescription: 'Major German OEM manufacturer of heavy industrial machinery.',
    validationStatus: 'Valid',
    validationReason: 'MX record verified & mailbox responsive',
    aiClassification: 'High Priority Buyer',
    aiScore: 94,
    aiConfidence: 0.96,
    aiReasoning: 'Tier-1 German OEM importer with active annual procurement for industrial valves (HS 8481.80.10).',
    aiRecommendedApproach: 'Direct container export pricing (CIF Hamburg) & technical OEM specification matching.',
    leadStatus: 'Qualified',
    outreachStatus: 'Not Contacted',
  },
  {
    companyName: 'Apex Fluid Controls LLC',
    contactName: 'Robert Sterling',
    jobTitle: 'VP of Supply Chain',
    email: 'r.sterling@apexfluidcontrols.com',
    phone: '+1 713 555 0192',
    website: 'https://apexfluidcontrols.com',
    country: 'USA',
    city: 'Houston',
    industry: 'Engineering & Controls',
    productInterest: 'Submersible Slurry Pumps',
    buyerType: 'Distributor',
    hsCode: '8413.70.20',
    technicalStandards: ['ANSI/HI 1.3', 'ISO 5199'],
    certificationsRequired: ['ISO 9001:2015', 'ATEX Explosion Proof'],
    preferredIncoterms: 'FOB',
    targetPort: 'Port of Houston',
    roleCategory: 'Procurement',
    annualImportVolume: '$1M - $2.5M',
    companyDescription: 'Texas-based distributor of high-pressure fluid pumps.',
    validationStatus: 'Valid',
    validationReason: 'Active commercial business address',
    aiClassification: 'High Priority Buyer',
    aiScore: 90,
    aiConfidence: 0.93,
    aiReasoning: 'Established US distributor seeking international OEM pump supply partners (HS 8413.70.20).',
    aiRecommendedApproach: 'Propose distributor margin structure & express sample air-freight shipment.',
    leadStatus: 'Valid',
    outreachStatus: 'Not Contacted',
  },
  {
    companyName: 'Gulf Power Equipment Trading FZE',
    contactName: 'Tariq Al-Mansoor',
    jobTitle: 'Chief Quality Inspector',
    email: 'tariq.mansoor@gulfpowerequip.ae',
    phone: '+971 4 398 7700',
    website: 'https://gulfpowerequip.ae',
    country: 'UAE',
    city: 'Dubai',
    industry: 'Electrical Equipment',
    productInterest: 'High Voltage Transformers',
    buyerType: 'Wholesaler',
    hsCode: '8504.23.00',
    technicalStandards: ['IEC 60076', 'IEEE C57'],
    certificationsRequired: ['KEMA Type Test Report', 'ISO 14001'],
    preferredIncoterms: 'CIF',
    targetPort: 'Jebel Ali Port',
    roleCategory: 'Quality QA/QC',
    annualImportVolume: '$5M+',
    companyDescription: 'Leading Dubai importer of power transmission transformers.',
    validationStatus: 'Valid',
    validationReason: 'Verified commercial MX domain',
    aiClassification: 'Medium Priority Buyer',
    aiScore: 82,
    aiConfidence: 0.90,
    aiReasoning: 'Middle East distributor with high-capacity transformer demand.',
    aiRecommendedApproach: 'Share product catalog with CE/IEC certification compliance docs.',
    leadStatus: 'Qualified',
    outreachStatus: 'Not Contacted',
  },
  {
    companyName: 'Nippon Precision Drive Corp',
    contactName: 'Hiroshi Tanaka',
    jobTitle: 'Chief Component Engineer',
    email: 'h.tanaka@nipponprecisiondrive.co.jp',
    phone: '+81 6 6203 1100',
    website: 'https://nipponprecisiondrive.co.jp',
    country: 'Japan',
    city: 'Osaka',
    industry: 'Manufacturing Equipment',
    productInterest: 'CNC Machine Components & Gears',
    buyerType: 'Manufacturer',
    hsCode: '8483.40.10',
    technicalStandards: ['AGMA 2001', 'ISO 6336'],
    certificationsRequired: ['Ultrasonic Flaw Cert', 'Dimensional Report'],
    preferredIncoterms: 'CFR',
    targetPort: 'Osaka Port',
    roleCategory: 'Engineering',
    annualImportVolume: '$500k - $1M',
    companyDescription: 'Precision machining manufacturer requiring custom forged steel gears.',
    validationStatus: 'Risky',
    validationReason: 'Generic contact address; role mailbox detected',
    aiClassification: 'Medium Priority Buyer',
    aiScore: 74,
    aiConfidence: 0.85,
    aiReasoning: 'High technical requirement Japanese manufacturer.',
    aiRecommendedApproach: 'Send CAD drawing specifications and ISO 9001 quality audit reports.',
    leadStatus: 'Imported',
    outreachStatus: 'Not Contacted',
  },
  {
    companyName: 'Equipamentos Industriais Brasil Ltda',
    contactName: 'Carlos Silva',
    jobTitle: 'Director of Procurement',
    email: 'carlos@equipamentosbrasil.com.br',
    phone: '+55 11 3209 8811',
    website: 'https://equipamentosbrasil.com.br',
    country: 'Brazil',
    city: 'São Paulo',
    industry: 'Industrial Supplies',
    productInterest: 'Hydraulic Fittings & Flanges',
    buyerType: 'Distributor',
    hsCode: '7307.91.00',
    technicalStandards: ['SAE J514', 'ISO 8434-1'],
    certificationsRequired: ['ISO 9001', 'NACE MR0175'],
    preferredIncoterms: 'FOB',
    targetPort: 'Santos Port',
    roleCategory: 'Procurement',
    annualImportVolume: '$250k - $500k',
    companyDescription: 'São Paulo supplier of heavy hydraulic fittings.',
    validationStatus: 'Valid',
    validationReason: 'Verified business email address',
    aiClassification: 'High Priority Buyer',
    aiScore: 86,
    aiConfidence: 0.91,
    aiReasoning: 'Strong demand for hydraulic fittings in South American industrial sector.',
    aiRecommendedApproach: 'Offer FOB port shipment quotes and 30-day payment terms.',
    leadStatus: 'Valid',
    outreachStatus: 'Not Contacted',
  },
];

export const seedTemplates = [
  {
    name: 'European Industrial OEM Technical & Logistics Pitch',
    subject: 'OEM Supply of {{product_name}} (HS {{hs_code}}) for {{company_name}} in {{country}}',
    body: `Hello {{contact_name}},

I noticed that {{company_name}} operates as a prominent industrial manufacturer in the {{industry}} sector in {{country}}.

As an ISO 9001 & CE certified export manufacturer of {{product_name}} (HS Code: {{hs_code}}), we partner with leading industrial OEMs across Europe to supply high-precision components with guaranteed compliance and competitive {{incoterm}} {{target_port}} shipping terms.

Our production facility supports:
- Full compliance with ASME B16.34 & DIN EN 10204 3.1 Mill Test Certificates
- 100% Hydrostatic and Ultrasonic Non-Destructive Testing (NDT)
- Flexible container load export dispatch (20ft/40ft FCL or LCL)

Would you be available for a brief 10-minute technical introduction call next week to review OEM specifications and sample export terms?

Best regards,
Alex Rivera
Export Sales Director | Apex Industrial Exports`,
    product: 'Industrial Valves & Actuators',
    targetCountry: 'Germany',
    buyerType: 'Importer',
    targetRoleCategory: 'Procurement',
    incotermDefault: 'CIF',
    hsCodeContext: '8481.80.10',
    language: 'English',
    status: 'Active',
  },
  {
    name: 'US Engineering & Distributor Partnership Outreach',
    subject: 'B2B Distribution & OEM Supply: {{product_name}} for {{company_name}}',
    body: `Hi {{contact_name}},

Reaching out from Apex Industrial Exports. We specialize in engineering and manufacturing high-durability {{product_name}} for North American industrial distributors.

Given {{company_name}}'s established presence in {{country}}, we would like to explore establishing a direct factory supply partnership for your regional market.

Key Commercial & Technical Advantages:
1. Direct factory wholesale pricing with competitive {{incoterm}} {{target_port}} terms
2. Complete EN 10204 3.1 Mill Certificates & ISO 9001 audit documentation
3. CAD step file customization and private label packaging

Could I send over our latest technical catalog and container freight lead time schedule for your review?

Warm regards,
Alex Rivera
Apex Industrial Exports`,
    product: 'Submersible Slurry Pumps',
    targetCountry: 'USA',
    buyerType: 'Distributor',
    targetRoleCategory: 'Engineering',
    incotermDefault: 'FOB',
    hsCodeContext: '8413.70.20',
    language: 'English',
    status: 'Active',
  },
];
